### ISSUE TITLE
Solr cloud provided zookeeper cluster in unhealthy state

### ISSUE THREAD

**Issue by krishnachalla-hv** [apache/solr-operator#213]
I have installed **v0.2.8** version of the operator, Sometimes one of the provided zookeeper instance goes into unhealthy state. I have used default values initialize zookeeper instance that are provided in the documentation. Here is my configuration:

```
apiVersion: v2
name: test
description: A Helm chart for intializing multi node solr cloud.
appVersion: 1.0.0
dependencies:
  - name: solr-operator
    version: 0.2.8
    repository: "https://apache.github.io/lucene-solr-operator/charts"
    condition: solr-operator.enabled

  - name: zookeeper-operator
    version: 0.3.0
    repository: "https://kubernetes-charts.banzaicloud.com"
    condition: zookeeper-operator.enabled

```
And the solr cloud yaml file:

```
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: {{ .Release.Name }}
spec:
  dataStorage:
    persistent:
      reclaimPolicy: Retain
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: "5Gi"
  replicas: 2
  solrImage:
    tag: 8.7.0
  solrJavaMem: "-Xms1g -Xmx3g"
  customSolrKubeOptions:
    podOptions:
      resources:
        limits:
          memory: "1G"
        requests:
          cpu: "65m"
          memory: "156Mi"
  zookeeperRef:
    provided:
      chroot: "/solr"
      persistence:
        reclaimPolicy: Retain
        spec:
          resources:
            requests:
              storage: "5Gi"
      replicas: 3
      zookeeperPodPolicy:
        resources:
          limits:
            memory: "1G"
          requests:
            cpu: "65m"
            memory: "156Mi"
  solrOpts: "-Dsolr.autoSoftCommit.maxTime=10000"
  solrGCTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
```

After applying the above configuration always 2nd zk pod will be in unhealthy state.[ZK pod error.log](https://github.com/apache/lucene-solr-operator/files/5951776/ZK.pod.error.log) But the remaining 2 ZK pods will be functioning properly. I logged into the the error pod and tried pinging like this this **ping t0-solrcloud-zookeeper-0.t0-solrcloud-zookeeper-headless.default.svc.cluster.local** I am getting the reply back.
![zk unhealthy state](https://user-images.githubusercontent.com/60733731/107374588-c348b100-6b0d-11eb-9b41-005861a15c9e.png)
