### ISSUE TITLE
Allow specifying the name of a TLS secret for the Ingress to support TLS termination at the Ingress

### ISSUE THREAD

**Issue by thelabdude** [apache/solr-operator#268]
Currently, the operator doesn't support TLS termination at the Ingress. Users can configure TLS all the way through from Ingress to Solr pods and between them. This would be an easy enhancement, but requires adding a field to the `solrAddressability.external` struct to hold the TLS secret name so that we can configure the Ingess with:

```
spec:
  tls:
    - hosts:
      - foo.bar.com
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: tls-secret
```
see: https://kubernetes.github.io/ingress-nginx/examples/tls-termination/

In the meantime, users will need to create their own Ingress instead of using the one created by the operator.
