### ISSUE TITLE
Allow configuration of zookeeper cluster configs via values.yaml

### ISSUE THREAD

**Issue by chaicesan** [apache/solr-operator#290]
As it stands we can't configure the lower level zookeeper cluster properties (e.g. zoo.cfg) via the solr-operator. I realised this recently when I was debugging one of our services and decided it's worth changing some zookeeper configs but there is no access to them. Specifically I am interested in [these](https://github.com/pravega/zookeeper-operator/blob/5e2c1bb3cc9d7aadff2011b1de01587b472ee9de/deploy/crds/zookeeper.pravega.io_zookeeperclusters_crd.yaml#L94) properties.

How I envision it working (give or take)

values.yaml
```
...
zookeeper:
    properties:
        initLimit: 10
        maxClientCnxns: 1000
        syncLimit: 5
        tickTime: 2000
...
```

If there are any questions then feel free to let me know.
