### ISSUE TITLE
Add possiblity to annotate addressability.external Ingress 

### ISSUE THREAD

**Issue by thomaswoeckinger** [apache/solr-operator#336]
When using `addressability.external.method=Ingress` the solr operator will create and configure an Ingress object.
Currently there is no way to configure additional annotations which are added to the created Ingress object.

This would be especially useful to enable features like passthrough or re-encrypt.

E.g. when using OKD `route.openshift.io/termination: passthrough` it is possible to passthrough the traffic to the already encrypted Solr endpoint.

**Comment by HoustonPutman** [comment]
you can add custom annotations to the Ingress at:

`customSolrKubeOptions.ingressOptions.annotations`

**Comment by thomaswoeckinger** [comment]
Tried various ways to configure none is working, also adding following yaml with -f as parameter did not work:

```
customSolrKubeOptions:
  ingressOptions:
    annotations:
      route.openshift.io/termination: passthrough
```

The created SolrCloud Object contains olny following values:

```
...
  customSolrKubeOptions:
    podOptions:
      resources: {}
      serviceAccountName: solr
```

Modifying the created SolrCloud object to 

```
...
  customSolrKubeOptions:
    podOptions:
      resources: {}
      serviceAccountName: solr
    ingressOptions:
      annotations:
        route.openshift.io/termination: passthrough
```

is working correctly.

So finally the issue here is i could not get the options into the SolrCloud object
