### ISSUE TITLE
Add possibility to annotate zookeeper to trigger rolling update

### ISSUE THREAD

**Issue by nosvalds** [apache/solr-operator#352]
You can manually trigger a restart of the solr pods by changing an annotation in `podOptions`

 ```
 apiVersion: solr.apache.org/v1beta1
 kind: SolrCloud
 spec:
   customSolrKubeOptions:
     podOptions:
           annotations:
             manualrestart: "2021-10-20T08:37:00Z"
```

This is currently not possible to do for the zookeeper pods managed by the solr-operator. It would be nice if you could add an annotation for the zookeeper config to manually trigger a restart like the solr pods.

Errors if you try to annotate zookeeperRef:
```
ValidationError(SolrCloud.spec.zookeeperRef.provided.zookeeperPodPolicy): unknown field "annotations" in org.apache.solr.v1beta1.SolrCloud.spec.zookeeperRef.provided.zookeeperPodPolicy;

ValidationError(SolrCloud.spec.zookeeperRef): unknown field "annotations" in org.apache.solr.v1beta1.SolrCloud.spec.zookeeperRef;
```

Full background from slack: https://kubernetes.slack.com/archives/CQSNS615F/p1634636068067300
