### ISSUE TITLE
JTS and Polygons jar file

### ISSUE THREAD

**Issue by fernaspiazu** [apache/solr-operator#364]
Hi,
Is there a way to install/download the library `jts-core` in the folder `SOLR_INSTALL/server/solr-webapp/webapp/WEB-INF/lib/`? As specified in the official guide: https://solr.apache.org/guide/8_10/spatial-search.html#jts-and-polygons-flat

Actually, I tried to put in the middle an `initContainer` that downloads such jar, but I get obviously a `Permission denied` from the Solr container since only root can write on the final solr container.

I tried also to set a `securityContext` only for my `initContainer`, in order to run as root, but that configuration has no effect in the `initContainer`, I think it is not seen by the Solr CRD.

```
podOptions:
  initContainers:
  - name: "install-jts-core"
    image: solr:8.9.0
    command: ['sh', '-c', 'wget -O /opt/solr-8.9.0/server/solr-webapp/webapp/WEB-INF/lib/jts-core-1.15.1.jar https://repo1.maven.org/maven2/org/locationtech/jts/jts-core/1.15.1/jts-core-1.15.1.jar']
    securityContext:   <--- this has no effect on SolrCloud CRD
      runAsUser: 0
```

Another disperate attempt was to set a `podSecurityContext.runAsUser: 0`, so for all containers in the pod, but Solr does not run as `root`, I discarded that option by the way.

Any hint/idea/solution please?

Thank you very much in advance.

**Comment by HoustonPutman** [comment]
Hello @fernaspiazu, this is a good question.

Starting with Solr Operator `v0.5.0`, you should be able to do the following:

1. Use the init container, and save it in an empty-dir volume. Mount this volume into your init-container at any location. 2. Mount this emtpy-dir jar volume in your Solr container, somewhere under the data path (`/var/solr/data/libs`).
3. Then use `SolrCloud.spec.additionalLibs=['/var/solr/data/libs']`. (Note this will only work for more recent solr versions, but that is fine since you are running `8.9.0`.

I recognize that the Solr documentation says the Jar has to be placed in WEB_INF/lib, but I really don't think that's possible given the Solr docker image.

Give this a try and let me know if it works.

**Comment by fernaspiazu** [comment]
Hi @HoustonPutman,

Thank you very much for your answer.

I have recently found a solution that may not be elegant, but works well in any version of Solr image, below a configuration example:

```yaml
podOptions:
  initContainers:
  - name: "install-jts-lib"
    image: solr:8.9.0
    command:
    - 'sh'
    - '-c'
    - |
      wget -O /tmp-webinf-lib/jts-core-1.15.1.jar https://repo1.maven.org/maven2/org/locationtech/jts/jts-core/1.15.1/jts-core-1.15.1.jar
      cp -R /opt/solr/server/solr-webapp/webapp/WEB-INF/lib/* /tmp-webinf-lib
    volumeMounts:
    - mountPath: /tmp-webinf-lib
      name: web-inf-lib
  volumes:
  - name: web-inf-lib
    source:
      emptyDir: {}
    defaultContainerMount:
      name: web-inf-lib
      mountPath: /opt/solr/server/solr-webapp/webapp/WEB-INF/lib
```

In this example, I create an `emptyDir` volume, attach it in any directory of the `initContainer`, but in the `target directory` of the final Solr image, this will empty the `WEB-INF/lib` directory, but since I'm using the same Solr image, I can copy the content of `WEB-INF/lib` (jars and folders) at the end.

The effect is that the final container will have all the content it should have had plus the `jts-core-1.15.1.jar` jar.

This works also with other files or libraries you want to bring in the Solr container.

Let me know what do you thing of this workaround 👍

Thank you again.
