### ISSUE TITLE
Accessing Solr without using an Ingress

### ISSUE THREAD

**Issue by gthvidsten** [apache/solr-operator#381]
The Solr Operator tutorial wants to use an Ingress so that Solr is available from outside Kubernetes. However, I don't want it to be available outside Kubernetes, only use it internally. Normally with a deployment you would create a Service that other pods connect to, but I can't see any services being installed using Helm.

How can other pods in the same cluster access Solr without having to make Solr available through an Ingress?

**Comment by janhoy** [comment]
You only need the ingress for external traffic. Applications running inside the cluster can use the service name for your cluster. Say you have a SolrCloud deployment called "example" with 2 pods, you will see that there is a `-common` service created that will load balance between the two pods, and you can also access each node with the `-0` and `-1` service names.

```
NAME                                          READY   STATUS                       RESTARTS
pod/example-solrcloud-0                       1/1     Running                      0       
pod/example-solrcloud-1                       1/1     Running                      0       

NAME                                          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)
service/example-solrcloud-common              ClusterIP      10.43.185.20    <none>        80/TCP 
service/example-solrcloud-0                   ClusterIP      10.43.69.190    <none>        80/TCP 
service/example-solrcloud-1                   ClusterIP      10.43.16.234    <none>        80/TCP 
```

**Comment by gthvidsten** [comment]
Thanks for the swift reply :)
I tried doing a `kubectl port-forward` to my "example-solrcloud-common" (8080 -> 80), but when I access http://localhost:8080 I get the following error in the shell:

```
Handling connection for 8080
E1202 15:12:11.516200   32672 portforward.go:400] an error occurred forwarding 8080 -> 8983: error forwarding port 8983 to pod 8a8abe2427d899d7e84f2e524fc43747d9e05ba49d23eda7bf263f731e66d6fa, uid : failed to execute portforward in network namespace "/var/run/netns/cni-8c979efc-93e7-93a6-a2fb-a78a8185e794": failed to dial 8983: dial tcp4 127.0.0.1:8983: connect: connection refused
```

**Comment by HoustonPutman** [comment]
You can override the image for that container with:

```yaml
busyBoxImage:
  repository: "busybox"
  tag: "1.28.0-glibc"
  pullPolicy: ""
  imagePullSecret: ""
```

This image is used for an init container that sets up the data directory/`solr.xml`.
And yes, the Solr Operator contains defaults that assume access to the default docker registry, docker hub. If you want to use a different repository then you need to set that for each image.

```yaml
image:
  repository: "solr"
  tag: ""
  pullPolicy: ""
  imagePullSecret: ""

zk:
  provided:
    image:
      repository: "pravega/zookeeper"
      tag: ""
      pullPolicy: IfNotPresent
      imagePullSecret: ""

busyBoxImage:
  repository: "busybox"
  tag: "1.28.0-glibc"
  pullPolicy: ""
  imagePullSecret: ""
```

**Comment by gthvidsten** [comment]
How can I do this in the `helm install` command?

**Comment by gthvidsten** [comment]
Ah, values.yaml... I remember seeing something about that.
The quickstart tutorial in the documentation said "we will create a yaml" but then proceeds without any yaml, and there's no examples as far as I've been able to find.
Do you have an example values.yaml file available?

**Comment by HoustonPutman** [comment]
Ahh I think that is a sentence left over from before the Solr helm chart existed. The best example `values.yaml` file is actually the default: https://github.com/apache/solr-operator/blob/v0.5.0/helm/solr/values.yaml

You don't need to (and shouldn't) include everything, since helm will use the default `values.yaml` as the starting point, then replace anything that is in your override values.yaml. So you can take the default values.yaml and remove anything that you don't want to change. For the example you have provided, you can merely use the following: (sets solr to use 8.4, uses a custom storage class name, and persistent storage for solr, and uses custom repositories for every image)

```yaml
image:
  repository: "custom.docker.repo/solr"
  tag: "8.4"

dataStorage:
  type: persistent
  persistent:
    pvc:
      storageClassName: "solr-storage"

zk:
  provided:
    image:
      repository: "custom.docker.repo/zookeeper"
    persistence:
      spec:
        storageClassName: "solr-storage"

busyBoxImage:
  repository: "custom.docker.repo/busybox"
```
