### ISSUE TITLE
Can't specify nodeSelector for SolrCloud / ZK / Busybox

### ISSUE THREAD

**Issue by gthvidsten** [apache/solr-operator#382]
**Problem**

If you have a multi platform node cluster (linux + windows) then you need to specify a `nodeSelector` to force a deployment to run on a specific node. Usually like this:
```
nodeSelector:
  kubernetes.io/os: linux
```

If you don't have this setting in place then K8s will place them on a node as K8s seems fit. When this node turns out to be a Windows node the images needed for SolrCloud will not be able to be pulled, with a generic `ErrImagePull` in the events for the pods.

Trying to set `nodeSelector` in the `values.yaml` doesn't work for the SolrCloud installation. There are no errors, it just seems to be ignored.

**Solution**

Make SolrCloud use `nodeSelector` settings if they are set, preferrably in `values.yaml`

**Comment by HoustonPutman** [comment]
Hello @gthvidsten , thanks for reporting this!

Did you try using `podOptions.nodeSelector` or just `nodeSelector` in the `values.yaml`?

**Comment by gthvidsten** [comment]
I only tried `nodeSelector`. I looked in the original `values.yaml` you linked me to in the other thread but couldn't find anything resembling `nodeSelector` to replace with, but looking again I can of course find the `podOptions.nodeSelector` you mention so I'll give that a try.

How is it used? Do I just put a value of `linux` for this setting, or do I need the full `kubernetes.io/os: linux`?

**Comment by HoustonPutman** [comment]
Use it exactly like you would on a pod, or podTemplate in a Deployment. The operator basically just takes the things you provide to podOptions, and puts them into the pod template in the StatefulSet unaltered.

So:
```yaml
podOptions:
  nodeSelector:
    kubernetes.io/os: linux
```

Also we try to keep the helm chart documentation pretty up-to-date, so searching through this page should help find any options: https://artifacthub.io/packages/helm/apache-solr/solr

**Comment by gthvidsten** [comment]
Thanks. Adding the `podOptions` worked wonders!
You should probably consider setting the `kubernetes.io/os: linux` as default, though.

**Comment by HoustonPutman** [comment]
ahhh so that pod options is for the Solr cluster.

For the zookeeper cluster, use the following in your SolrCloud resource:
```yaml
spec:
  zookeeperRef:
    provided:
      zookeeperPodPolicy:
        nodeSelector:
          kubernetes.io/os: linux
```

For the helm chart, you can pass this through:
```yaml
zk:
  provided:
    zookeeperPodPolicy:
      nodeSelector:
        kubernetes.io/os: linux
```

Sorry for omitting this earlier, those two are the only you will have to do unless you are also installing a Solr Prometheus Exporter, but that will be specified in a different resource.
