### ISSUE TITLE
LoadBalancer option for common service

### ISSUE THREAD

**Issue by otienoanyango** [apache/solr-operator#400]
I have a setup on Google Kubernetes Engine where I deploy a cluster in each of three regions. To index data, I need access from outside the cluster, but all I need is an internal IP.  I am using annotations that GKE provides for this but it requires being able to set `spec.Type: LoadBalancer` for the service.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
    networking.gke.io/load-balancer-type: Internal
spec:
  type: LoadBalancer
  ...
```

is there a way to set the type for the commonService
