### ISSUE TITLE
Problems with istio and prometheus

### ISSUE THREAD

**Issue by johgoe** [apache/solr-operator#427]
Seems that my cluster runs into https://github.com/prometheus/prometheus/issues/10213

the current port configuration of search-prom-exporter-solr-metrics service looks like
```
  ports:
  - name: solr-metrics
    port: 80
    protocol: TCP
    targetPort: 8080
```

but istio requires the http protocol to be definied by port name prefix

```
  ports:
  - name: http-solr-metrics
    port: 80
    protocol: TCP
    targetPort: 8080
```

or by appProtocol
```
  ports:
  - name: http-solr-metrics
    port: 80
    protocol: TCP
    targetPort: 8080
    appProtocol: http
```

I would prefer a solution which is able to add an app protocol

My current SolrPrometheusExporter looks like this

```
apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  name: search-prom-exporter
spec:
  customKubeOptions:
    podOptions:
      resources:
        requests:
          cpu: 300m
          memory: 900Mi
  solrReference:
    cloud:
      name: "search"
  numThreads: 6

```

My current serviceMonitor looks like this

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: controller-manager-metrics-monitor
spec:
  selector:
    matchLabels:
      solr-prometheus-exporter: search-prom-exporter
  namespaceSelector:
    matchNames:
      - search
  endpoints:
    - port: solr-metrics
      scheme: https
      tlsConfig:
        caFile: /etc/prometheus/secrets/istio.default/root-cert.pem
        certFile: /etc/prometheus/secrets/istio.default/cert-chain.pem
        insecureSkipVerify: true
        keyFile: /etc/prometheus/secrets/istio.default/key.pem
      interval: 10s
      scrapeTimeout: 10s

```

**Comment by sukolenvo** [comment]
Can this issue be reopened please? appProtocol is not set in the latest operator: https://github.com/apache/solr-operator/blob/e1e4c2b3866581601b8e765139901447cb06cfa2/controllers/util/solr_util.go#L915

http2+headless service is not supported by istio and in our practice workaround of setting protocol to tcp shows good results.

issue in istio: https://github.com/istio/istio/issues/49391#issuecomment-1954703454

As I understand previous fix of setting appProtocol to http caused was rolled back due to https://github.com/apache/solr-operator/issues/640

How about appProtocol: TCP?

**Comment by sukolenvo** [comment]
BTW here is zookeeper operator headless service: all ports are prefixed with `tcp-` - one more option to consider

```yaml
  ports:
    - name: tcp-client
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: tcp-quorum
      port: 2888
      protocol: TCP
      targetPort: 2888
    - name: tcp-leader-election
      port: 3888
      protocol: TCP
      targetPort: 3888
    - name: tcp-metrics
      port: 7000
      protocol: TCP
      targetPort: 7000
    - name: tcp-admin-server
      port: 8080
      protocol: TCP
      targetPort: 8080

```
