### ISSUE TITLE
Generate tls: entry for ingress entries even without a tls secret

### ISSUE THREAD

**Issue by matslindh** [apache/solr-operator#437]
The nginx ingress controller supports [using a default certificate for connections that don't have an explicit secret set](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#default-ssl-certificate) in their `tls` section. This default certificate is only used if a `secretName` is not provided. 

As far as I've been able to tell [from how the Ingress entry is created](https://github.com/apache/solr-operator/blob/395e83861cfe6bdb31dd3f1dcc94847af41ba01e/controllers/util/solr_util.go#L862) there is no way of getting an ingressTLS object added without providing some sort of secret.

Would it be possible to get an option to make the operator create an ingress entry with TLS, but without a secret name to make nginx use the default certificate? (which usually will be a wildcard certificate matching the at a certain level of the domainName given).

**Comment by HoustonPutman** [comment]
We can certainly make this a possibility. Can you provide an example ingress yaml using this default certificate functionality? Just want to make sure we understand how it works before trying to implement it.

**Comment by matslindh** [comment]
It's fairly simple; it's a regular `tls` section in the ingress entry, but without a reference to the secret. From another existing ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <ingressname>
  namespace: <namespace>
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - <hostname>
  rules:
    - host: <hostname>
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <servicename>
                port:
                  number: 8080
```

The relevant part is the `tls` section:

```yaml
  tls:
    - hosts:
      - <hostname>
```

.. in other ingress entries you'd have `secretName: ingress-demo-tls` together with the hostname as well, but since this has been configured as the default cert on the ingress controller instead (with a wildcard certificate), there isn't a need to provide a secret for this particular tls entry.

The nginx controller uses `default-ssl-certificate=namespace/secret-name` to allow this to be configured on a controller basis.
