### ISSUE TITLE
DataStorage as persistent with a defined pvcTemplate name prevents cluster creation

### ISSUE THREAD

**Issue by guilhermeblanco** [apache/solr-operator#438]
Currently if you attempt to create a cluster with a pvcTemplate containing a name, you experience the following error when describing the generated StatefulSet:

```yaml
Events:
  Type     Reason            Age                 From                    Message
  ----     ------            ----                ----                    -------
  Normal   SuccessfulCreate  37m                 statefulset-controller  create Claim xxx-solrcloud-0 Pod xxx-0 in StatefulSet xxx success
  Warning  FailedCreate      67s (x26 over 37m)  statefulset-controller  create Pod xxx-0 in StatefulSet xxx failed error: Pod "xxx-0" is invalid: [spec.containers[0].volumeMounts[0].name: Not found: "data", spec.initContainers[0].volumeMounts[1].name: Not found: "data"]
``` 

Here is the mapped Helm values (consuming apache-solr/solr chart) that generates this issue:

```yaml
dataStorage:
  type: "persistent"
  capacity: "120Gi"
  persistent:
    pvc:
      name: "${local.name}"
      reclaimPolicy: "Retain"
      storageClassName: "ebs"
```
