### ISSUE TITLE
SolrClouds status version is wrong

### ISSUE THREAD

**Issue by cdmikechen** [apache/solr-operator#445]
I've created a solr cloud (operator 0.5.1) with custrom registry, and I found the image version in status was wrong. 
Here is my CR:
```yaml
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: solr-project1
  namespace: project-1
spec:
  solrLogLevel: INFO
  solrSecurity:
    authenticationType: Basic
  zookeeperRef:
    provided:
      chroot: /
      config: {}
      image:
        pullPolicy: IfNotPresent
        repository: 'harbor.xxx.com:5000/apache/pravega/zookeeper'
        tag: 0.2.13
      replicas: 3
      zookeeperPodPolicy:
        resources: {}
  busyBoxImage:
    repository: 'harbor.xxx.com:5000/platform/busybox'
    tag: 1.28.0-glibc
  solrJavaMem: '-Xms1g -Xmx2g'
  dataStorage: {}
  solrAddressability:
    commonServicePort: 80
    podPort: 8983
  solrImage:
    repository: 'harbor.xxx.com:5000/apache/solr'
    tag: '8.11'
  replicas: 3
  updateStrategy:
    managed: {}
    method: Managed
  customSolrKubeOptions: {}
status:
  podSelector: 'solr-cloud=solr-project1,technology=solr-cloud'
  targetVersion: '8.11'
  internalCommonAddress: 'http://solr-project1-solrcloud-common.project-1'
  upToDateNodes: 3
  solrNodes:
    - internalAddress: >-
        http://solr-project1-solrcloud-0.solr-project1-solrcloud-headless.project-1:8983
      name: solr-project1-solrcloud-0
      ready: true
      specUpToDate: true
      version: 5000/apache/solr
    - internalAddress: >-
        http://solr-project1-solrcloud-1.solr-project1-solrcloud-headless.project-1:8983
      name: solr-project1-solrcloud-1
      ready: true
      specUpToDate: true
      version: 5000/apache/solr
    - internalAddress: >-
        http://solr-project1-solrcloud-2.solr-project1-solrcloud-headless.project-1:8983
      name: solr-project1-solrcloud-2
      ready: true
      specUpToDate: true
      version: 5000/apache/solr
  backupRestoreReady: false
  version: 5000/apache/solr
  zookeeperConnectionInfo:
    chroot: /
    externalConnectionString: N/A
    internalConnectionString: >-
      solr-project1-solrcloud-zookeeper-0.solr-project1-solrcloud-zookeeper-headless.project-1.svc.cluster.local:2181,solr-project1-solrcloud-zookeeper-1.solr-project1-solrcloud-zookeeper-headless.project-1.svc.cluster.local:2181,solr-project1-solrcloud-zookeeper-2.solr-project1-solrcloud-zookeeper-headless.project-1.svc.cluster.local:2181
  replicas: 3
  readyReplicas: 3

```
