### ISSUE TITLE
Target port of common and headless services are 0 in GKE Autopilot clusters

### ISSUE THREAD

**Issue by alfonsomunozpomer** [apache/solr-operator#470]
I created a SolrCloud on a [GKE Autopilot cluster](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview) with the following YAML:
```yaml
# https://apache.github.io/solr-operator/example/test_solrcloud.yaml
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: gxa
  namespace: jenkins-gene-expression
spec:
  dataStorage:
    persistent:
      reclaimPolicy: Retain
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: "15Gi"
  replicas: 2
  solrImage:
    tag: 8.7.0
  solrJavaMem: "-Xms1g -Xmx3g"
#  solrModules:
#    - jaegertracer-configurator
#    - ltr
  customSolrKubeOptions:
    podOptions:
      resources:
        limits:
          memory: "1G"
        requests:
          cpu: "65m"
          memory: "156Mi"
  zookeeperRef:
    provided:
#      chroot: "/this/will/be/auto/created"
      persistence:
        spec:
          storageClassName: fast
          resources:
            requests:
              storage: "1Gi"
      replicas: 3
      zookeeperPodPolicy:
        resources:
          limits:
            memory: "512Mi"
          requests:
            cpu: "65m"
            memory: "156Mi"
#  solrOpts: "-Dsolr.autoSoftCommit.maxTime=10000"
  solrGCTune: "-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8"
```

The target port of the headless and common services is set to 0, which is a minor annoyance because I need to create another service to do port-forwarding.

![image](https://user-images.githubusercontent.com/4425744/188873178-0c339bdc-1319-481e-8faf-cfe53877a66a.png)

It looks like the reason is that the `targetPort` is set to `solr-client`, rather than 8983.

This is the relevant block in the headless service:
```yaml
  - appProtocol: http
    name: solr-client
    port: 8983
    protocol: TCP
    targetPort: solr-client
```

And this is the one from the client service:
```yaml
  - appProtocol: http
    name: solr-client
    port: 80
    protocol: TCP
    targetPort: solr-client
```

Is this expected behaviour or something specific to GKE clusters?
