### ISSUE TITLE
Servicemonitor for prometheus exporter is referring to cluster port instead of metrics  pod port

### ISSUE THREAD

**Issue by sanjay3290** [apache/solr-operator#483]
I have followed the solr operator documentation to configure SolrPrometheusExporter, however after creating the servicemonitor, the service endpoint is going inactive. After further troubleshooting, i realized the metric server is trying to connect to port 80 whereas the metrics server is running on port 8080. Is it possible to pass port into service monitor?

Get "http://x.x.x.x:80/metrics": dial tcp x.x.x.x:80: connect: connection refused

**Comment by HoustonPutman** [comment]
Can you provide the yaml for the service monitor you created?

**Comment by sanjay3290** [comment]
Hello @HoustonPutman, Below is the Servicemonitor yaml , i used the default provided in SolrOperator Documentation.


apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: solr-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      solr-prometheus-exporter: solr-dev-prom-exporter
  namespaceSelector:
    matchNames:
    - solr-dev
  endpoints:
  - port: solr-metrics
    interval: 20s

**Comment by HoustonPutman** [comment]
So you are using a serviceMonitor, and the Solr metrics service is listening on port 80, or at least it should be... The pod is listening on port 8080, but the service forwards that 80 -> 8080 when sending the request to the pod.

I have almost the exact same thing working correctly.

What version of the prometheus stack are you running? Also can you provide information on your Kube cluster? (version, vendor, etc) I have a feeling there's an issue with your networking.

**Comment by sanjay3290** [comment]
you are right, thats how its supposed to work. However the service endpoint in prometheus targets is referencing to http://podIP:90/metrics and due to that, the connection is getting refused. My other default service endpoints for prometheus are working as expected.

Prometheus :
Chart:prometheus-15.16.1
Version:2.39.1   
Kubernetes:
AWS EKS, Version:1.22

**Comment by HoustonPutman** [comment]
Are you sure you don't have a podMonitor defined as well?

Looks like there might be a bug in the prometheus operator? In the meantime you can use `targetPort` instead to set `8080`. [Here are the available options](https://github.com/prometheus-operator/prometheus-operator/blob/5cfb4da102374d5f0284f463e8f11482705a6651/pkg/apis/monitoring/v1/types.go#L1257) under `endpoints`.

**Comment by koboltmarky** [comment]
We have the same problem here. We are using the solr-operator 0.6 and prometheus 2.39.1 hosted in gke version 1.21.
I deployed the solr prometheus exporter with the following snippet:

```
apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  name: solr-prom-exporter
spec:
  customKubeOptions:
      resources:
        requests:
          cpu: 300m
          memory: 900Mi
  solrReference:
    basicAuthSecret: solr-cloud-k8s-oper-secret 
    cloud:
      name: "apache-solr"
  numThreads: 6
```

As you can see in the screenshot prometheus tries to connect to the pod on port 80 which is the wrong port.


![Screenshot from 2022-12-01 16-17-22](https://user-images.githubusercontent.com/8583001/205090598-b500124a-a8d0-410e-a9b3-0950633022db.png)

Our workaround is to add a prometheus scraping annotation to the exporter pod:

```
spec:
  customKubeOptions:
    podOptions:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http

```

**Comment by HoustonPutman** [comment]
In that screenshot, is the `10.110.6.70` IP address the service ClusterIP or the pod IP? If it's the service's then there is something wrong with kubernetes. If its the pod, then Prometheus shouldn't be trying to contact the pod at all, it should be contacting the service IP...

**Comment by sanjay3290** [comment]
> We have the same problem here. We are using the solr-operator 0.6 and prometheus 2.39.1 hosted in gke version 1.21. We aren't using the prometheus operator. I deployed the solr prometheus exporter with the following snippet:
> 
> ```
> apiVersion: solr.apache.org/v1beta1
> kind: SolrPrometheusExporter
> metadata:
>   name: solr-prom-exporter
> spec:
>   customKubeOptions:
>       resources:
>         requests:
>           cpu: 300m
>           memory: 900Mi
>   solrReference:
>     basicAuthSecret: solr-cloud-k8s-oper-secret 
>     cloud:
>       name: "apache-solr"
>   numThreads: 6
> ```
> 
> As you can see in the screenshot prometheus tries to connect to the pod on port 80 which is the wrong port.
> 
> ![Screenshot from 2022-12-01 16-17-22](https://user-images.githubusercontent.com/8583001/205090598-b500124a-a8d0-410e-a9b3-0950633022db.png)
> 
> Our workaround is to add a prometheus scraping annotation to the exporter pod:
> 
> ```
> spec:
>   customKubeOptions:
>     podOptions:
>       annotations:
>         prometheus.io/port: "8080"
>         prometheus.io/path: /metrics
>         prometheus.io/scrape: "true"
>         prometheus.io/scheme: http
> ```

even after adding pod annotation, prometheus still looking at port 80 on pod IP in my case. Something is seriously wrong with this.below is my exporter config.

```
apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  name: solr-prom-exporter
spec:
  customKubeOptions:
    podOptions:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
      resources:
        requests:
          cpu: 300m
          memory: 900Mi
  solrReference:
    cloud:
      name: ["eks"](<img width="1898" alt="Screenshot 2022-12-01 at 3 54 04 PM" src="https://user-images.githubusercontent.com/24948667/205167285-48f6b9d7-4d70-4069-91b2-34125507e018.png">)
  numThreads: 6
```

**Comment by koboltmarky** [comment]
> In that screenshot, is the `10.110.6.70` IP address the service ClusterIP or the pod IP? If it's the service's then there is something wrong with kubernetes. If its the pod, then Prometheus shouldn't be trying to contact the pod at all, it should be contacting the service IP...

It is the pod ip

**Comment by koboltmarky** [comment]
> even after adding pod annotation, prometheus still looking at port 80 on pod IP in my case. Something is seriously wrong with this.below is my exporter config.

The old failed target will still exits but there should be a new target which should works.

**Comment by HoustonPutman** [comment]
Can you share your prometheus scraping config? This seems to be a prometheus issue...

**Comment by tiimbz** [comment]
We are having the same issue. The `prometheus.io/port` annotation is set to port `80`, which doesn't correspond with the port of the pod. This causes Prometheus to fail to scrape the service endpoint.

We've also bypassed the problem by enabling scraping of the pods directly: 

```
  customKubeOptions:
    podOptions:
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/scheme: http
```
