### ISSUE TITLE
solr cloud backup gcs

### ISSUE THREAD

**Issue by vipul-06** [apache/solr-operator#506]
I have created solrcloud using the yaml defined below
```
`apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: example
  namespace: dev-backend
spec:
  backupRepositories:
    - name: "gcs-backups-1"
      gcs:
        bucket: "vipul-test-bucket" # Required
        gcsCredentialSecret:
          name: "newsecret"
          key: "my-key.json"
  replicas: 3
  solrImage:
    tag: 9.0.0`
```
I am taking backup of my solr collections in gcs bucket

My solr backup yaml is as below

```
apiVersion: solr.apache.org/v1beta1
kind: SolrBackup
metadata:
  name: gcs-backup
  namespace: dev-backend
spec:
  solrCloud: example
  repositoryName: "gcs-backups-1"
  collections:
    - demo
    - test
    - new
```
My backup is starting but not getting anything on my bucket it is empty. 
Also my solrbackup is not getting completed it is as follows

```
NAME           CLOUD     STARTED   FINISHED   SUCCESSFUL   NEXTBACKUP   AGE
gcs-backup     example   60m                                            60m
local-backup   example   4h20m     true       true                      4h20m
```

I firstly created a pvc backup it got completed but my gcs backup is started but not finishing also no data in my bucket
