### ISSUE TITLE
Ability to add additional volumes to Zookeeper Pods

### ISSUE THREAD

**Issue by hmontesdeoca** [apache/solr-operator#534]
Hello,

I am currently using Azure to set up aks clusters utilizing solr-cloud helm charts and the provided zookeeper ensemble. I want to mount zookeeper logs onto a Azure File Share but I cant seem to specify a pvc for the zk provided ensemble. It only seems to accept a 'spec' as some sort of reference. How can I specify a PVC for zookeeper? Can I mount directly to the logs directory for zookeeper pods?
```
 zk:
    provided:
      persistence:
        spec:
          storageClassName:  "solr"
          #can I specify a path, volume, volume mount, or pvc?
```
