### ISSUE TITLE
Could not find a backup repository with name `solr-backup-s3-repo`

### ISSUE THREAD

**Issue by anilkhichar** [apache/solr-operator#593]
Please suggest any pointers for debugging. 

Is there any API where we can get the list of SolrOperator registered backup repositories?
Also, for S3 backup, does the Operator first download the backup data on disk and then execute the S3 cp/sync? 

Any internal detail would be helpful to debug the core issue.

**Error:**
```
2023-07-18T23:18:54.905Z        
ERROR   controller-runtime.manager.controller.solrbackup        
Error while taking SolrCloud backup     
{"reconciler group": "solr.apache.org", 
"reconciler kind": "SolrBackup",
 "name": "solr-backup", 
"namespace": "ns-solrcloud-int", 
"error": "Received bad response code of 500 from solr with response: 
{\n  \"responseHeader\":
{\n    \"status\":500,\n    \"QTime\":0},\n  \"error\":{\n    
\"msg\":\"Could not find a backup repository with name solr-backup-s3-repo\",
\n    \"trace\":\"java.lang.NullPointerException: 
Could not find a backup repository with name solr-backup-s3-repo\\
n\\tat 
java.base/java.util.Objects.requireNonNull(Unknown Source)\\n\\
tat org.apache.solr.core.backup.repository.
BackupRepositoryFactory.newInstance(BackupRepositoryFactory.java:74)
```

- **Solrbackup Setup**
`kubectl edit solrcloud solrsetup`

  ```
  backupRepositories:
  - name: "solr-backup-s3-repo"
    s3:
      region: "us-west-2"
      bucket: "<solr-s3-bucket>"
  ```

- **SolrBackup**
  ```
  ---
  apiVersion: solr.apache.org/v1beta1
  kind: SolrBackup
  metadata:
    name: "solr-backup"
  spec:
    repositoryName: "solr-backup-s3-repo"
    solrCloud: "solrsetup"
    collections:
      - mycollection
  ```

**Comment by anilkhichar** [comment]
Thank you @HoustonPutman for looking into this.

We are using Solr 9.2.0 with SolrOperator 0.5.1.

**Comment by HoustonPutman** [comment]
Can you provide your full SolrCloud specification? Are you using a custom solr xml, if so then you will need to add the backup repository yourself.

**Comment by anilkhichar** [comment]
Thank you @HoustonPutman for the guidance. Yes, we are using custom solr xml and that was the root cause. I wish, the solr backup document would have mentioned it. I will raise PR for that separately.

**The Resolution:**
1. Configure S3 jars/lib path in the sharedPath
1. Configure S3 repository in the custom solr xml
    ```
    <?xml version="1.0" encoding="UTF-8" ?>
    <solr>
      <str name="sharedLib">${solr.sharedLib:},${solr.install.dir}/contrib/s3-repository/lib</str>
      <solrcloud>
      .....
      </solrcloud>
      <backup>
        <repository name="solr-backup-s3-repo" class="org.apache.solr.s3.S3BackupRepository">
          <str name="s3.bucket.name">solr-backup-s3-bucket</str>
          <str name="s3.region">us-east-1</str>
        </repository>
      </backup>
    </solr>
    ```
1. Then on top it, it’s regular Solr Operator backup/restore configurations:
    ```
    kubectl edit solrcloud my-solr-cloud
 
    solrBackup:
      enabled: "true"
      backupRepositories:
        name: "solr-backup-s3-repo"
        region: "us-east-1"
        bucket: "solr-backup-s3-bucket" 
    ```
1. Then on top it, it’s regular Solr Operator backup/restore configurations:
    ```
    apiVersion: solr.apache.org/v1beta1
    kind: SolrBackup
    metadata:
      name: dev-solr-backup
      namespace: solr-workload-namespace
    spec: 
      repositoryName: "solr-backup-s3-repo"
      solrCloud: "my-solr-cloud"
      collections: # upgraded solr operator versions can backup all available collections
        - my-collection
      recurrence: # Store one backup daily, and keep a week at a time.
        schedule: "@daily"
        maxSaved: 7
        disabled: false
    ```
