### ISSUE TITLE
unable to take solr backup using s3

### ISSUE THREAD

**Issue by kannanvr** [apache/solr-operator#597]
Hi Team,

Trying to take Solr backup to s3. Getting below error. 

![image](https://github.com/apache/solr-operator/assets/16012974/671bb308-9c12-46b3-b457-d68c398b1605)

some directory are created in s3, but no data in it.
```
s3://solr/solrbkp-country/country/
[2023-08-02 22:06:29 IST]     0B index/77b5e96f-c787-449d-86c3-d15a3dd96fa2
[2023-08-02 22:06:29 IST]     0B shard_backup_metadata/
[2023-08-02 22:06:29 IST]     0B zk_backup_0/
```

Kindly refer the solrCloud.spec for backuprepositories and solrBackup yaml (Also collection country was created and inserted few data as well).
```
  backupRepositories:
  - name: "s3-backup"
    s3:
      baseLocation: "/"
      bucket: "solr"
      endpoint: "http://x.x.x.x"
      region: "us-east-1"
      credentials:
        accessKeyIdSecret:
          name: s3-cred
          key: access_key
        secretAccessKeySecret:
          name: s3-cred
          key: secret_key
---
apiVersion: solr.apache.org/v1beta1
kind: SolrBackup
metadata:
  name: solrbkp
  namespace: solr-cluster-2
spec:
  repositoryName: "s3-backup"
  solrCloud: test1
  collections:
    - country
  recurrence: # Store one backup daily, and keep a week at a time.
    schedule: "@every 5m"
    maxSaved: 7
```
