### ISSUE TITLE
Prometheus exporter high memory usage

### ISSUE THREAD

**Issue by stibi** [apache/solr-operator#658]
Hello,
we have trouble with solr exporter, it's very hungry for memory, it needs around ~6G of RAM, which is a lot and I can't figure out why.

Can I ask you any hint?

It's pretty much default setup, nothing custom:

SolrCloud 9.3.0. Nothing too much custom for the exporter deployment:

```
apiVersion: solr.apache.org/v1beta1
kind: SolrPrometheusExporter
metadata:
  name: solr-exporter
spec:
  customKubeOptions:
    podOptions:
      resources:
        requests:
          cpu: 500m
          memory: 3072Mi
        limits:
          cpu: 2000m
          memory: 6912Mi
      envVars:
        - name: JAVA_HEAP
          value: 6000m
  solrReference:
    cloud:
      name: "solr-cloud"
  numThreads: 6
```

<img width="1005" alt="Screenshot 2023-11-21 at 13 23 19" src="https://github.com/apache/solr-operator/assets/57834/9ad48b32-1af0-45b6-b805-f4d2fc7c050b">
