### ISSUE TITLE
Adding support to dynamic value in values.yaml

### ISSUE THREAD

**Issue by idolaman** [apache/solr-operator#661]
First of all this project is amazing!

I encountered an issue when i tried to use this chart as an dependency to my chart.

in my use case i want to be able to give a dynamic value in values yaml.
for an example i want that the configmap name to be dynamic because i want to deploy multiple solr cluters in the same k8s envirement.
my chart `values.yaml`
```yaml
global:
  configmap: idolaman

solr:
  podOptions:
    volumes:
      - name: my-configmap
        source:
          configMap:
            name: "{{ .Values.global.configmap }}"
         
...
```
my Chart.yaml

```yaml
name: idolaman-solr
dependencies:
  - name: solr
    ....
```

an solution might be change the `solr` chart to evaluate using tpl every value it gets
