### ISSUE TITLE
Add the ability to add Environment variables as a configmap

### ISSUE THREAD

**Issue by kharouny** [apache/solr-operator#677]
Statefulsets have the option to add Environment variables as configmaps like so...

```        
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: my-app-container
        image: your-image:tag
        envFrom:
        - configMapRef:
            name: my-app-config
```

Currently the SolrCloud config [only supports adding additional EnvVariables in line.](https://github.com/apache/solr-operator/blob/8e986e60a82fcd577fe55e882e23a5491f4d3014/api/v1beta1/common_types.go#L78)
