### ISSUE TITLE
Support replicaPlacementFactory in solr.xml

### ISSUE THREAD

**Issue by janhoy** [apache/solr-operator#691]
With https://issues.apache.org/jira/browse/SOLR-15782 in 9.5, we got support for [configuring placement plugins in solr.xml](https://solr.apache.org/guide/solr/latest/configuration-guide/configuring-solr-xml.html#the-replicaplacementfactory-element):

```xml
<replicaPlacementFactory class="org.apache.solr.cluster.placement.plugins.AffinityPlacementFactory">
  <int name="minimalFreeDiskGB">10</int>
  <int name="prioritizedFreeDiskGB">200</int>
</replicaPlacementFactory>
```

The operator could support a similar configuration option. Perhaps it can be made generic:

```yaml
replicaPlacementFactory:
  class: org.apache.solr.cluster.placement.plugins.AffinityPlacementFactory
  config:
    minimalFreeDiskGB: 10
    prioritizedFreeDiskGB: 200
```

I think we could add support for it before the minimum version is 9.5, since if the user does not configure the feature, nothing will be added to `solr.xml`. This can be documented.
