### ISSUE TITLE
SolrOperator leads to 404 

### ISSUE THREAD

**Issue by rmoreno123** [apache/solr-operator#713]
Hello,

I have been following this tutorial `https://solr.apache.org/operator/articles/explore-v030-gke.html` 

However, I have been unsuccessful in getting a solr instance to run.

Is there a step or something I may be missing that may be leading to this 404? For testing purposes I am not enabling TLS, I would like to just get the admin dashboard up and running in a production environment. My pods seem to be running with no issues without any warnings or errors in logs.

This is not my first time trying to setup Solr on my cluster, previous attempts included signed certificates with TLS enabled, and basic authentication, but I seem to be led to the same 404 response. I have also executed a shell session directly inside a running pod and made a curl request to localhost:8983 and seem to be getting a valid response. So I am unsure what this issue might be. 

I currently try to access this deployment through the ingress created by the Solr Operator CRD and visit the given IP address. Am I missing something crucial in the tutorial? Any help would be greatly appreciated.

****explore-SolrCloud.yaml:****
```
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: explore
spec:

  solrAddressability:
    commonServicePort: 443
    external:
      hideNodes: true
      domainName: **HIDDEN**
      method: Ingress
      nodePortOverride: 443
      useExternalAddress: false
    podPort: 8983

  customSolrKubeOptions:
    ingressOptions:
      annotations:
        kubernetes.io/ingress.class: "nginx"
    podOptions:
      resources:
        limits:
          memory: 3Gi
        requests:
          cpu: 700m
          memory: 3Gi
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 2Gi
      reclaimPolicy: Delete
  replicas: 3
  solrImage:
    repository: solr
    tag: 8.8.2
  solrJavaMem: -Xms500M -Xmx500M
  updateStrategy:
    method: StatefulSet
  zookeeperRef:
    provided:
      chroot: /explore
      image:
        pullPolicy: IfNotPresent
        repository: pravega/zookeeper
        tag: 0.2.9
      persistence:
        reclaimPolicy: Delete
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      replicas: 3
      zookeeperPodPolicy:
        resources:
          limits:
            memory: 500Mi
          requests:
            cpu: 250m
            memory: 500Mi
```

```
$ kubectl get all
NAME                                                    READY   STATUS    RESTARTS   AGE
pod/explore-solrcloud-0                                 1/1     Running   0          42m
pod/explore-solrcloud-1                                 1/1     Running   0          43m
pod/explore-solrcloud-2                                 1/1     Running   0          43m
pod/explore-solrcloud-zookeeper-0                       1/1     Running   0          82m
pod/explore-solrcloud-zookeeper-1                       1/1     Running   0          81m
pod/explore-solrcloud-zookeeper-2                       1/1     Running   0          80m
pod/solr-operator-6f54f69bb5-qx7bq                      1/1     Running   0          84m
pod/solr-operator-zookeeper-operator-76c9cb86bf-mvscn   1/1     Running   0          84m

NAME                                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
service/explore-solrcloud-0                        ClusterIP   34.118.236.23    <none>        443/TCP                                        63m
service/explore-solrcloud-1                        ClusterIP   34.118.228.141   <none>        443/TCP                                        63m
service/explore-solrcloud-2                        ClusterIP   34.118.237.173   <none>        443/TCP                                        63m
service/explore-solrcloud-common                   ClusterIP   34.118.232.190   <none>        443/TCP                                        82m
service/explore-solrcloud-headless                 ClusterIP   None             <none>        8983/TCP                                       82m
service/explore-solrcloud-zookeeper-admin-server   ClusterIP   34.118.235.233   <none>        8080/TCP                                       82m
service/explore-solrcloud-zookeeper-client         ClusterIP   34.118.228.236   <none>        2181/TCP                                       82m
service/explore-solrcloud-zookeeper-headless       ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP,7000/TCP,8080/TCP   82m

NAME                                               READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/solr-operator                      1/1     1            1           84m
deployment.apps/solr-operator-zookeeper-operator   1/1     1            1           84m

NAME                                                          DESIRED   CURRENT   READY   AGE
replicaset.apps/solr-operator-6f54f69bb5                      1         1         1       84m
replicaset.apps/solr-operator-zookeeper-operator-76c9cb86bf   1         1         1       84m

NAME                                           READY   AGE
statefulset.apps/explore-solrcloud             3/3     82m
statefulset.apps/explore-solrcloud-zookeeper   3/3     82m
```
