### ISSUE TITLE
Unable to pass shareProcessNamespace to PodOptions

### ISSUE THREAD

**Issue by tommylogik** [apache/solr-operator#716]
I have a need to add `shareProcessNamespace` for use within a sidecar for some solr thread debugging and there doesn't seem to be a way to pass this option.

This should be able to be passed within the Solr Operator CRD.
```
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: explore
spec:
  customSolrKubeOptions:
    podOptions:
      shareProcessNamespace: true
```

Currently i have to use use kyverno to mutate the pod after the operator creates the statefulset and would love to be able to remove that destructive option for a more graceful approach in adding it to the helm chart values file.
