### ISSUE TITLE
Mounting a volume to container is not clear

### ISSUE THREAD

**Issue by jamesla** [apache/solr-operator#736]
I am trying to attach a volume from a configmap to an init container but it is not entirely clear how to do it from the CRD spec. I've also been unable to find any examples of somebody doing this:

The code so far:

```yaml
---
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: test
spec:
  replicas: 1
  customSolrKubeOptions:
    podOptions:
      volumes:
        - source: 
            configMap:
          name: configset
          defaultContainerMount:
            mountPath: /config
            name: config.xml
      sidecarContainer:
        - name: config-loader
          image: alpine/curl:latest
          command:
            - "sh"
            - "-c"
            - "ls -la /config"
          volumeMounts:
            - name: configset
              mountPath: /config

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: configset
data:
  config.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
     <config>
      ...
     </config>
```

It runs and the /config mount exists but it is always empty.

1. Are there any examples of volume mounts with this operator?
2. What am I doing wrong?

**Comment by mcarroll1** [comment]
I've encountered a similar issue here https://github.com/apache/solr-operator/issues/675 (referencing an older issue here: https://github.com/apache/solr-operator/issues/484). 

I can't say exactly what's wrong here, but my guess would be that you need to add a line under `configMap` referencing the name (gleaning this from this doc: https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#populate-a-volume-with-data-stored-in-a-configmap)

```
        - source: 
            configMap:
              name: configset
          name: configset
```
