### ISSUE TITLE
Recommended approach for loading a schema and configset using the operator

### ISSUE THREAD

**Issue by jamesla** [apache/solr-operator#740]
I'm struggling to load a schema and a configset using the operator.

In my docker-compose I do it like this:

```yaml
  config-loader:
    image: alpine/curl:latest
    container_name: solr-init
    volumes:
      - ./solrconfig.xml:/solrconfig.xml
      - ./managed-schema.xml:/managed-schema.xml
    depends_on:
      solr-cloud:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c '
      curl -s -X PUT --header "Content-Type:application/octet-stream" --data-binary @solrconfig.xml "http://solr-cloud:8983/api/cluster/configs/llm_papers_configset/solrconfig.xml";
      curl -X PUT --header "Content-Type:application/octet-stream" --data-binary @managed-schema.xml "http://solr-cloud:8983/api/cluster/configs/llm_papers_configset/managed-schema.xml";
      curl "solr-cloud:8983/solr/admin/collections?action=CREATE&name=llm_papers&numShards=1&replicationFactor=1&collection.configName=llm_papers_configset&wt=json&zkHost=zookeeper:2181";
      '
```

I have tried using a sidecarContainer however I feel like that is the wrong approach since solrcloud api needs to be ready in order to receive the requests which creates a race condition.

I've also read through the CRD options but I can't find anything related to configsets or schemas.

What is the recommended way to approach this using the operator?
