### ISSUE TITLE
Use custom name for the ServiceAccount of Zookeeper operator

### ISSUE THREAD

**Issue by vesk0win** [apache/solr-operator#750]
Hello,

I am trying to run 2 Solr cloud clusters in the same K8S namespace. The names of the resources are different except the one for the ServiceAccount of the Zookeeper operator. This leads to the following warning and constant syncing in both Solr operator ArgoCD applications:

```
ServiceAccount/zookeeper-operator is part of applications argocd/solr-operator-compliant and solr-operator
```

I was not able to find a setting in the CRD of ZookeeperCluster or SolrCloud to set a different name for the ServiceAccount. Is there such way? Thanks!

**Comment by saurabh-adhikari** [comment]
By default, the Zookeeper Operator creates a ServiceAccount named zookeeper-operator when installed via the Solr Operator dependency chart. This behavior can be modified by overriding the configurable parameters in [solr-operator](https://github.com/apache/solr-operator/blob/0ffddb6a4be25ffb3fdad6cb3ffe759d89c5fcf2/helm/solr-operator/README.md#running-the-solr-operator) and [zookeeper-operator](https://github.com/pravega/zookeeper-operator/tree/master/charts/zookeeper-operator#configuration) through values.yaml.

To create a ServiceAccount with a custom name in the default namespace (where another Solr Operator exists), following configuration can be applied:

```yaml
solr-operator:
  serviceAccount:
    create: false
    name: zookeeper-operator-custom

zookeeper-operator:
  serviceAccount:
    create: true
    name: zookeeper-operator-custom

```
