### ISSUE TITLE
Security.json is never copied to Zookeeper while creating Solr 9.8.0 Clusters

### ISSUE THREAD

**Issue by jdgiddings** [apache/solr-operator#762]
When creating a SolrCloud 9.8.0 cluster using version 0.9.0 of Solr Operator, security.json is never coped to Zookeeper. The `setup-zk` container appears to have all the correct information, including the $SECURITY_JSON variable. The only logs are a single line: `No security.json found. Put new security.json in ZK`

I have other SolrCloud clusters that have been upgraded from 9.4 -> 9.8 and they work fine, but they have a completely different command in `setup-zk`

One thing I noticed is that all of the `setup-zk` init containers finish running before a zookeeper is online, possibly creating a race condition

#720 Seems related

I believe 0e76152755bc1b66fb2f703b58df2271158444ca introduced the new behavior

**Comment by jdgiddings** [comment]
Here is a minimal example where the bug occurs. Please excuse the Azure stuff, we're hosting it on AKS

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: security-json
  namespace: dev
data:
  security.json: REDACTED
  type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: solr-basic-auth
  namespace: dev
data:
  password: REDACTED
  username: REDACTED
type: kubernetes.io/basic-auth
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: solr-config
  namespace: dev  
data:
  solr.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <solr>
        <int name="maxBooleanClauses">10240</int>
        <solrcloud>
        <str name="host">${host:}</str>
        <int name="hostPort">${hostPort:80}</int>
        <str name="hostContext">${hostContext:solr}</str>
        <bool name="genericCoreNodeNames">${genericCoreNodeNames:true}</bool>
        <int name="zkClientTimeout">${zkClientTimeout:30000}</int>
        <int name="distribUpdateSoTimeout">${distribUpdateSoTimeout:600000}</int>
        <int name="distribUpdateConnTimeout">${distribUpdateConnTimeout:60000}</int>
        <str name="zkCredentialsProvider">${zkCredentialsProvider:org.apache.solr.common.cloud.DefaultZkCredentialsProvider}</str>
        <str name="zkACLProvider">${zkACLProvider:org.apache.solr.common.cloud.DefaultZkACLProvider}</str>
        </solrcloud>
        <shardHandlerFactory name="shardHandlerFactory"
        class="HttpShardHandlerFactory">
        <int name="socketTimeout">${socketTimeout:600000}</int>
        <int name="connTimeout">${connTimeout:60000}</int>
        </shardHandlerFactory>      
    </solr>
---
apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: test
  namespace: dev
spec:
  availability:
    podDisruptionBudget:
      enabled: false
  busyBoxImage:
    repository: busybox
    tag: 1.28.0-glibc
  customSolrKubeOptions:
    configMapOptions:
      providedConfigMap: solr-config
    podOptions:
      nodeSelector:
        kubernetes.azure.com/scalesetpriority: spot
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
  dataStorage:
    persistent:
      pvcTemplate:
        metadata: {}
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: premium-ssd-v2
      reclaimPolicy: Retain
  replicas: 3
  scaling:
    populatePodsOnScaleUp: true
    vacatePodsOnScaleDown: true
  solrAddressability:
    commonServicePort: 80
    podPort: 8983
  solrImage:
    repository: solr
    tag: 9.8.0
  solrJavaMem: '-Xms8G -Xmx8G'
  solrLogLevel: INFO
  solrSecurity:
    authenticationType: Basic
    basicAuthSecret: solr-basic-auth
    bootstrapSecurityJson:
      key: security.json
      name: security-json
  zookeeperRef:
    provided:
      image:
        pullPolicy: IfNotPresent
        repository: pravega/zookeeper
      maxUnavailableReplicas: 1
      persistence:
        reclaimPolicy: Retain
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          storageClassName: standard-ssd-zrs
      replicas: 3
      zookeeperPodPolicy:
        nodeSelector:
          kubernetes.azure.com/scalesetpriority: spot
        securityContext:
          fsGroup: 1000
        tolerations:
          - effect: NoSchedule
            key: kubernetes.azure.com/scalesetpriority
            operator: Equal
            value: spot
```
